version: '3.8'
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '3050:80'
  postgres:
    image: postgres
    env_file:
      - .env
  redis:
    image: redis
  api:
    depends_on:
      - postgres
      - redis
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    env_file:
      - ./server/.env
    volumes:
      - /app/node_modules # don't try to overwrite this folder
      - ./server:/app
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
    # Fixes bug where websocket connection is fixed to default port 3000
      - WDS_SOCKET_PORT=0
  worker:
    depends_on:
      - redis
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    env_file:
      - ./worker/.env